import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.locator('form i').first().click();
  await page.getByRole('option', { name: 'Admin' }).click();
  await page.getByText('-- Select --').click();
  await page.getByRole('option', { name: 'Enabled' }).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('Password123');
  await page.getByRole('textbox', { name: 'Type for hints...' }).click();
  await page.getByRole('textbox', { name: 'Type for hints...' }).fill('a');
  await page.getByText('Ranga Akunuri').click();
  await page.getByRole('textbox').nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Ranga Akunuri');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).fill('Ranga _Akunuri1');
  await page.getByRole('textbox').nth(2).press('ArrowLeft');
  await page.getByRole('textbox').nth(2).fill('Ranga_Akunuri1');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('Password123');
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('Password123');
  await page.getByRole('button', { name: 'Save' }).click();
  //await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/admin/viewSystemUsers');
 // await page.getByRole('row', { name: ' Ranga_Akunuri Admin Ranga' }).locator('span i').click();
});